# -*- coding: utf-8 -*-
"""Basketball player statistics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q7ppGURNpHblFOonbKh6_nE3aYqDZ7Uh

User can use it to track player's statistics
Concept:
The user enter the players data manual.
The program supports atleast 3 basketball players.
Each player's data include player's name and the points scored.
Program use funtions to organise logic.
For loop to process multiple players.
The program will give each player a rating according to their points scored.
Else-if statement to determine preformance level.
The program calculates and display average points highest scorer and lowest scorer.
"""

def get_preformance_level(points):
  if points >= 30:
    return "star player"
  elif points >= 20:
    return "great player"
  elif points >= 10:
    return "good player"
  elif points >= 1:
    return "improving player"
  else:
    return "did not score"
def calculate_avg(players):
  total = 0
  for player in players:
    total += player["points"]
  return total / len(players)
def highest_scorer(players):
  top = players[0]
  for player in players:
    if player["points"]>top["points"]:
      top = player
  return top
def lowest_scorer(players):
  low = players[0]
  for player in players:
    if player["points"]<low["points"]:
      low = player
  return low

players = []
num_players = int(input("Enter number of basketball players"))
for i in range(num_players):
  print(f"\nPlayers{i + 1}")
  name = input("Enter player's name")
  points = int(input("Points scored"))
  players.append({
      "name" : name,
      "points" : points
  })
print("\nplayer report\n")
for player in players:
  level = get_preformance_level(player["points"])
  print(
        f"Name: {player['name']} | "
        f"Points: {player['points']} | "
        f"Level: {level}"
    )
print("\nSummary")
avg = calculate_avg(players)
top = highest_scorer(players)
low = lowest_scorer(players)
print(f"Average Points: {avg:.2f}")
print(f"Top Scorer: {top['name']}({top['points']}points)")
print(f"Lowest Scorer: {low['name']}({low['points']}points)")